import img from "~/assets/img";
import mp3 from "~/assets/mp3";

const again = [];

const treding = [];

const recommend = [
  {
    id: 0,
    title: "Cao ốc 20",
    name: "Bray x DatG",
    view: "15tr",
    img: img.caooc20,
    lyric: mp3.caooc20,
  },
  {
    id: 1,
    title: "Anh sẽ ổn thôi",
    name: "Anh Tú",
    view: "10tr",
    img: img.anhseonthoi,
    lyric: mp3.anhseonthoi,
  },
  {
    id: 2,
    title: "Luôn yêu đời remix",
    name: "Đen, Cheng & Low G",
    view: "1.5tr",
    img: img.luonyeudoiremix,
    lyric: mp3.luonyeudoiremix,
  },
  {
    id: 3,
    title: "Luôn yêu đời",
    name: "Đen, Cheng",
    view: "24tr",
    img: img.luonyeudoi,
    lyric: mp3.luonyeudoi,
  },
  {
    id: 4,
    title: "Anh chưa thương em đến vậy đâu",
    name: "Lady Mây",
    view: "24tr",
    img: img.anhchuathuongemdenvaydau,
    lyric: mp3.anhchuathuongemdenvaydau,
  },
  {
    id: 5,
    title: "An thần",
    name: "Low if Thắng",
    view: "24tr",
    img: img.anthan,
    lyric: mp3.anthan,
  },
  {
    id: 6,
    title: "Đau để trưởng thành",
    name: "OnlyC",
    view: "24tr",
    img: img.daudetruongthanh,
    lyric: mp3.daudetruongthanh,
  },
  {
    id: 7,
    title: "Diễn viên tồi",
    name: "Đen ft Thành Bùi, Cadillac",
    view: "24tr",
    img: img.dienvientoi,
    lyric: mp3.dienvientoi,
  },
  {
    id: 8,
    title: "Ex's Hate Me(Part 2)",
    name: "AMEE x B RAY",
    view: "24tr",
    img: img.exhateme2,
    lyric: mp3.exhateme2,
  },
  {
    id: 9,
    title: "Hết thương cạn nhớ",
    name: "Đức Phúc",
    view: "24tr",
    img: img.hetthuongcannho,
    lyric: mp3.hetthuongcannho,
  },
  {
    id: 10,
    title: "Không thích",
    name: "Low G",
    view: "24tr",
    img: img.khongthich,
    lyric: mp3.khongthich,
  },
  {
    id: 11,
    title: "Người đi bao",
    name: "tlinh if Low G",
    view: "24tr",
    img: img.nguoidibao,
    lyric: mp3.nguoidibao,
  },
  {
    id: 12,
    title: "Vỡ Tan",
    name: "Trịnh Thăng Bình x Hiền Hồ",
    view: "24tr",
    img: img.votan,
    lyric: mp3.votan,
  },
  {
    id: 13,
    title: "‘3107’ full album",
    name: "W/n ft (267,Nâu, Dươngg)",
    view: "24tr",
    img: img.wn3107,
    lyric: mp3.wn3107,
  },
];

const allSong = [
  {
    id: 0,
    title: "Cao ốc 20",
    name: "Bray x DatG",
    view: "15tr",
    img: img.caooc20,
    lyric: mp3.caooc20,
  },
  {
    id: 1,
    title: "Anh sẽ ổn thôi",
    name: "Anh Tú",
    view: "10tr",
    img: img.anhseonthoi,
    lyric: mp3.anhseonthoi,
  },
  {
    id: 2,
    title: "Luôn yêu đời remix",
    name: "Đen, Cheng & Low G",
    view: "1.5tr",
    img: img.luonyeudoiremix,
    lyric: mp3.luonyeudoiremix,
  },
  {
    id: 3,
    title: "Luôn yêu đời",
    name: "Đen, Cheng",
    view: "24tr",
    img: img.luonyeudoi,
    lyric: mp3.luonyeudoi,
  },
  {
    id: 4,
    title: "Anh chưa thương em đến vậy đâu",
    name: "Lady Mây",
    view: "24tr",
    img: img.anhchuathuongemdenvaydau,
    lyric: mp3.anhchuathuongemdenvaydau,
  },
  {
    id: 5,
    title: "An thần",
    name: "Low if Thắng",
    view: "24tr",
    img: img.anthan,
    lyric: mp3.anthan,
  },
  {
    id: 6,
    title: "Đau để trưởng thành",
    name: "OnlyC",
    view: "24tr",
    img: img.daudetruongthanh,
    lyric: mp3.daudetruongthanh,
  },
  {
    id: 7,
    title: "Diễn viên tồi",
    name: "Đen ft Thành Bùi, Cadillac",
    view: "24tr",
    img: img.dienvientoi,
    lyric: mp3.dienvientoi,
  },
  {
    id: 8,
    title: "Ex's Hate Me(Part 2)",
    name: "AMEE x B RAY",
    view: "24tr",
    img: img.exhateme2,
    lyric: mp3.exhateme2,
  },
  {
    id: 9,
    title: "Hết thương cạn nhớ",
    name: "Đức Phúc",
    view: "24tr",
    img: img.hetthuongcannho,
    lyric: mp3.hetthuongcannho,
  },
  {
    id: 10,
    title: "Không thích",
    name: "Low G",
    view: "24tr",
    img: img.khongthich,
    lyric: mp3.khongthich,
  },
  {
    id: 11,
    title: "Người đi bao",
    name: "tlinh if Low G",
    view: "24tr",
    img: img.nguoidibao,
    lyric: mp3.nguoidibao,
  },
  {
    id: 12,
    title: "Vỡ Tan",
    name: "Trịnh Thăng Bình x Hiền Hồ",
    view: "24tr",
    img: img.votan,
    lyric: mp3.votan,
  },
  {
    id: 13,
    title: "‘3107’ full album",
    name: "W/n ft (267,Nâu, Dươngg)",
    view: "24tr",
    img: img.wn3107,
    lyric: mp3.wn3107,
  },
];

export { again, treding, recommend, allSong };
